[package]
name = "mex"
description = "A maths expression parser/evaluator"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/Zac-Garby/mex"
repository = "https://github.com/Zac-Garby/mex"
version = "0.1.0"
authors = ["Zac Garby <zacgarby@icloud.com>"]

[dependencies]
